INSERT OR IGNORE INTO maschines (name, exercise_def_id, increment_step, max_reps) VALUES
    ('Beinpresse 45°', 'leg_press', 5.0, 8),
    ('Schulterpresse', 'shoulder_press_machine', 2.5, 8),
    ('Beinbeuger (Leg Curl)', 'leg_curl_machine', 2.5, 8),
    ('Butterfly (Peck Deck)', 'butterfly_machine', 2.5, 10),
    ('Seitheben (Maschine / Kabel)', 'lateral_raise_machine', 2.5, 8),
    ('Dips', 'dips', 2.5, 10),
    ('Klimmzüge (Pull-Ups)', 'pull_ups', 2.5, 10),
    ('Preacher Curls Bank / Maschine', 'preacher_curl', 2.5, 15),
    ('Preacher Hammer Curl Maschine', 'preacher_hammer_curl', 2.5, 12),
    ('Reverse Butterfly (Pec Deck)', 'reverse_butterfly_machine', 2.5, 8),
    ('Beinstrecker', 'leg_extension_machine', 2.5, 8),
    ('Bauchmaschine', 'abs_machine', 2.5, 8),
    ('Enges Rudern (Kabel / Kabelturm)', 'close_grip_row', 2.5, 8),
    ('Trizepsdrücken liegend (Kurzhanteln)', 'db_skullcrusher', 2.5, 14),
    ('Wadenheben an der Beinpresse', 'calf_press_leg_press', 5.0, 15);